from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PICK_MainWindow(object):
    def setupUi(self, PICK_MainWindow):
        PICK_MainWindow.setObjectName("PICK_MainWindow")
        PICK_MainWindow.resize(1092, 687)
        self.filteringPage = QtWidgets.QWidget(PICK_MainWindow)
        self.filteringPage.setObjectName("filteringPage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.filteringPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1091, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.filteringButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.filteringButton.setObjectName("filteringButton")
        self.horizontalLayout.addWidget(self.filteringButton)
        self.graphButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.graphButton.setObjectName("graphButton")
        self.horizontalLayout.addWidget(self.graphButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label1.setObjectName("label1")
        self.horizontalLayout_8.addWidget(self.label1)
        self.fromDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.fromDate.setObjectName("fromDate")
        self.horizontalLayout_8.addWidget(self.fromDate)
        self.toDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.toDate.setObjectName("toDate")
        self.horizontalLayout_8.addWidget(self.toDate)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label2.setObjectName("label2")
        self.horizontalLayout_9.addWidget(self.label2)
        self.fromTime = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.fromTime.setObjectName("fromTime")
        self.horizontalLayout_9.addWidget(self.fromTime)
        self.toTime = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.toTime.setObjectName("toTime")
        self.horizontalLayout_9.addWidget(self.toTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.keywordInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.keywordInput.setObjectName("keywordInput")
        self.horizontalLayout_10.addWidget(self.keywordInput)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logEntryDisplay = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.logEntryDisplay.setWidgetResizable(True)
        self.logEntryDisplay.setObjectName("logEntryDisplay")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 490, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.logEntryDisplay.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.logEntryDisplay)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.verticalLayoutWidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_5.addWidget(self.verticalScrollBar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 491, 549))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_6.addWidget(self.scrollArea_2)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.verticalLayoutWidget)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_6.addWidget(self.verticalScrollBar_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        PICK_MainWindow.setCentralWidget(self.filteringPage)
        self.menubar = QtWidgets.QMenuBar(PICK_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        PICK_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PICK_MainWindow)
        self.statusbar.setObjectName("statusbar")
        PICK_MainWindow.setStatusBar(self.statusbar)
        self.actionExport_CSV = QtWidgets.QAction(PICK_MainWindow)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionExport_Settings = QtWidgets.QAction(PICK_MainWindow)
        self.actionExport_Settings.setObjectName("actionExport_Settings")
        self.actionImport_Settings = QtWidgets.QAction(PICK_MainWindow)
        self.actionImport_Settings.setObjectName("actionImport_Settings")
        self.actionExport_PDF = QtWidgets.QAction(PICK_MainWindow)
        self.actionExport_PDF.setObjectName("actionExport_PDF")
        self.actionTeam_Settings = QtWidgets.QAction(PICK_MainWindow)
        self.actionTeam_Settings.setObjectName("actionTeam_Settings")
        self.actionDirectory_Settings = QtWidgets.QAction(PICK_MainWindow)
        self.actionDirectory_Settings.setObjectName("actionDirectory_Settings")
        self.menuFile.addAction(self.actionExport_CSV)
        self.menuFile.addAction(self.actionExport_PDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Settings)
        self.menuFile.addAction(self.actionImport_Settings)
        self.menuSettings.addAction(self.actionTeam_Settings)
        self.menuSettings.addAction(self.actionDirectory_Settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(PICK_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(PICK_MainWindow)

    def retranslateUi(self, PICK_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        PICK_MainWindow.setWindowTitle(_translate("PICK_MainWindow", "PICK"))
        self.filteringButton.setText(_translate("PICK_MainWindow", "Filtering"))
        self.graphButton.setText(_translate("PICK_MainWindow", "Graph"))
        self.label1.setText(_translate("PICK_MainWindow", "Date Rage:"))
        self.label2.setText(_translate("PICK_MainWindow", "Time Range:"))
        self.label.setText(_translate("PICK_MainWindow", "Keyword:"))
        self.pushButton_3.setText(_translate("PICK_MainWindow", "Search"))
        self.menuFile.setTitle(_translate("PICK_MainWindow", "File"))
        self.menuSettings.setTitle(_translate("PICK_MainWindow", "Settings"))
        self.actionExport_CSV.setText(_translate("PICK_MainWindow", "Export CSV"))
        self.actionExport_Settings.setText(_translate("PICK_MainWindow", "Export Settings"))
        self.actionImport_Settings.setText(_translate("PICK_MainWindow", "Import Settings"))
        self.actionExport_PDF.setText(_translate("PICK_MainWindow", "Export PDF"))
        self.actionTeam_Settings.setText(_translate("PICK_MainWindow", "Team Settings"))
        self.actionDirectory_Settings.setText(_translate("PICK_MainWindow", "Directory Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PICK_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_PICK_MainWindow()
    ui.setupUi(PICK_MainWindow)
    PICK_MainWindow.show()
    sys.exit(app.exec_())
