from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PICK_SettingView(object):
    def setupUi(self, PICK_SettingView):
        PICK_SettingView.setObjectName("PICK_SettingView")
        PICK_SettingView.setWindowModality(QtCore.Qt.NonModal)
        PICK_SettingView.resize(1281, 779)
        PICK_SettingView.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(PICK_SettingView)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.OptionView = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OptionView.sizePolicy().hasHeightForWidth())
        self.OptionView.setSizePolicy(sizePolicy)
        self.OptionView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OptionView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OptionView.setObjectName("OptionView")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.OptionView)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.OV_GroupBox = QtWidgets.QGroupBox(self.OptionView)
        self.OV_GroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.OV_GroupBox.setObjectName("OV_GroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.OV_GroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.OV_TeamConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_TeamConfigButton.setObjectName("OV_TeamConfigButton")
        self.verticalLayout_7.addWidget(self.OV_TeamConfigButton)
        self.OV_EventConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_EventConfigButton.setObjectName("OV_EventConfigButton")
        self.verticalLayout_7.addWidget(self.OV_EventConfigButton)
        self.OV_DirectoryConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_DirectoryConfigButton.setObjectName("OV_DirectoryConfigButton")
        self.verticalLayout_7.addWidget(self.OV_DirectoryConfigButton)
        self.OV_VectorConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_VectorConfigButton.setObjectName("OV_VectorConfigButton")
        self.verticalLayout_7.addWidget(self.OV_VectorConfigButton)
        self.OV_ChangeConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_ChangeConfigButton.setObjectName("OV_ChangeConfigButton")
        self.verticalLayout_7.addWidget(self.OV_ChangeConfigButton)
        self.OV_IconConfigButton = QtWidgets.QPushButton(self.OV_GroupBox)
        self.OV_IconConfigButton.setObjectName("OV_IconConfigButton")
        self.verticalLayout_7.addWidget(self.OV_IconConfigButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.gridLayout_4.addWidget(self.OV_GroupBox, 0, 0, 2, 2)
        self.OVMainViewLine = QtWidgets.QFrame(self.OptionView)
        self.OVMainViewLine.setFocusPolicy(QtCore.Qt.NoFocus)
        self.OVMainViewLine.setAcceptDrops(False)
        self.OVMainViewLine.setAutoFillBackground(False)
        self.OVMainViewLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.OVMainViewLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.OVMainViewLine.setObjectName("OVMainViewLine")
        self.gridLayout_4.addWidget(self.OVMainViewLine, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.OptionView, 0, 0, 1, 1)
        self.StackView = QtWidgets.QStackedWidget(self.centralwidget)
        self.StackView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackView.sizePolicy().hasHeightForWidth())
        self.StackView.setSizePolicy(sizePolicy)
        self.StackView.setObjectName("StackView")
        self.TeamConfigView = QtWidgets.QWidget()
        self.TeamConfigView.setObjectName("TeamConfigView")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.TeamConfigView)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.IPAddressLineEdit = QtWidgets.QLineEdit(self.TeamConfigView)
        self.IPAddressLineEdit.setObjectName("IPAddressLineEdit")
        self.gridLayout_17.addWidget(self.IPAddressLineEdit, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem1, 8, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem2, 6, 2, 7, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem3, 18, 2, 1, 1)
        self.TeamConfigConnectpushButton = QtWidgets.QPushButton(self.TeamConfigView)
        self.TeamConfigConnectpushButton.setObjectName("TeamConfigConnectpushButton")
        self.gridLayout_17.addWidget(self.TeamConfigConnectpushButton, 10, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem4, 17, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 1000000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_17.addItem(spacerItem5, 11, 1, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem6, 7, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem7, 13, 2, 1, 1)
        self.NoOfConnectionslineEdit = QtWidgets.QLineEdit(self.TeamConfigView)
        self.NoOfConnectionslineEdit.setObjectName("NoOfConnectionslineEdit")
        self.gridLayout_17.addWidget(self.NoOfConnectionslineEdit, 5, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem9, 14, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem10, 20, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem11, 21, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem12, 22, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem13, 23, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem14, 25, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem15, 26, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem16, 27, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem17, 28, 2, 1, 1)
        self.TeamConfigGroupBox = QtWidgets.QGroupBox(self.TeamConfigView)
        self.TeamConfigGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TeamConfigGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TeamConfigGroupBox.setObjectName("TeamConfigGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.TeamConfigGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TeamConfigTopContentFrame = QtWidgets.QFrame(self.TeamConfigGroupBox)
        self.TeamConfigTopContentFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TeamConfigTopContentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TeamConfigTopContentFrame.setObjectName("TeamConfigTopContentFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.TeamConfigTopContentFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3.addWidget(self.TeamConfigTopContentFrame)
        self.LeadCheckBox = QtWidgets.QCheckBox(self.TeamConfigGroupBox)
        self.LeadCheckBox.setObjectName("LeadCheckBox")
        self.verticalLayout_3.addWidget(self.LeadCheckBox)
        self.ConnectionStatus = QtWidgets.QLabel(self.TeamConfigGroupBox)
        self.ConnectionStatus.setObjectName("ConnectionStatus")
        self.verticalLayout_3.addWidget(self.ConnectionStatus)
        self.LeadIPLabel = QtWidgets.QLabel(self.TeamConfigGroupBox)
        self.LeadIPLabel.setEnabled(True)
        self.LeadIPLabel.setObjectName("LeadIPLabel")
        self.verticalLayout_3.addWidget(self.LeadIPLabel)
        self.IPConnectionLabel = QtWidgets.QLabel(self.TeamConfigGroupBox)
        self.IPConnectionLabel.setObjectName("IPConnectionLabel")
        self.verticalLayout_3.addWidget(self.IPConnectionLabel)
        self.gridLayout_17.addWidget(self.TeamConfigGroupBox, 0, 1, 7, 1)
        self.StackView.addWidget(self.TeamConfigView)
        self.EventConfigView = QtWidgets.QWidget()
        self.EventConfigView.setObjectName("EventConfigView")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.EventConfigView)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.SaveEventPushButton = QtWidgets.QPushButton(self.EventConfigView)
        self.SaveEventPushButton.setObjectName("SaveEventPushButton")
        self.gridLayout_13.addWidget(self.SaveEventPushButton, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem18, 3, 0, 1, 1)
        self.EventConfigGroupBox = QtWidgets.QGroupBox(self.EventConfigView)
        self.EventConfigGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventConfigGroupBox.sizePolicy().hasHeightForWidth())
        self.EventConfigGroupBox.setSizePolicy(sizePolicy)
        self.EventConfigGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.EventConfigGroupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.EventConfigGroupBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.EventConfigGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.EventConfigGroupBox.setStyleSheet("")
        self.EventConfigGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EventConfigGroupBox.setObjectName("EventConfigGroupBox")
        self.EventNameLineEdit = QtWidgets.QLineEdit(self.EventConfigGroupBox)
        self.EventNameLineEdit.setGeometry(QtCore.QRect(160, 70, 631, 21))
        self.EventNameLineEdit.setObjectName("EventNameLineEdit")
        self.EventDescriptionLineEdit = QtWidgets.QLineEdit(self.EventConfigGroupBox)
        self.EventDescriptionLineEdit.setGeometry(QtCore.QRect(160, 110, 631, 21))
        self.EventDescriptionLineEdit.setObjectName("EventDescriptionLineEdit")
        self.EventStartLineEdit = QtWidgets.QLineEdit(self.EventConfigGroupBox)
        self.EventStartLineEdit.setGeometry(QtCore.QRect(160, 150, 631, 21))
        self.EventStartLineEdit.setObjectName("EventStartLineEdit")
        self.EventEndLineEdit = QtWidgets.QLineEdit(self.EventConfigGroupBox)
        self.EventEndLineEdit.setGeometry(QtCore.QRect(160, 190, 631, 21))
        self.EventEndLineEdit.setObjectName("EventEndLineEdit")
        self.EventNameLabel = QtWidgets.QLabel(self.EventConfigGroupBox)
        self.EventNameLabel.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.EventNameLabel.setObjectName("EventNameLabel")
        self.EventDescriptionLabel = QtWidgets.QLabel(self.EventConfigGroupBox)
        self.EventDescriptionLabel.setGeometry(QtCore.QRect(10, 110, 151, 16))
        self.EventDescriptionLabel.setObjectName("EventDescriptionLabel")
        self.EventStartTimestampLabel = QtWidgets.QLabel(self.EventConfigGroupBox)
        self.EventStartTimestampLabel.setGeometry(QtCore.QRect(10, 150, 141, 16))
        self.EventStartTimestampLabel.setObjectName("EventStartTimestampLabel")
        self.EventEndTimestampLabel = QtWidgets.QLabel(self.EventConfigGroupBox)
        self.EventEndTimestampLabel.setGeometry(QtCore.QRect(10, 190, 141, 16))
        self.EventEndTimestampLabel.setObjectName("EventEndTimestampLabel")
        self.gridLayout_13.addWidget(self.EventConfigGroupBox, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem19, 2, 0, 1, 1)
        self.StackView.addWidget(self.EventConfigView)
        self.DirectoryConfigView = QtWidgets.QWidget()
        self.DirectoryConfigView.setObjectName("DirectoryConfigView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DirectoryConfigView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DirectoryConfigGroupbox = QtWidgets.QGroupBox(self.DirectoryConfigView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DirectoryConfigGroupbox.sizePolicy().hasHeightForWidth())
        self.DirectoryConfigGroupbox.setSizePolicy(sizePolicy)
        self.DirectoryConfigGroupbox.setAlignment(QtCore.Qt.AlignCenter)
        self.DirectoryConfigGroupbox.setObjectName("DirectoryConfigGroupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DirectoryConfigGroupbox)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 4, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 2, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem22, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 6, 1, 1, 1)
        self.WhiteTeamLineEdit = QtWidgets.QLineEdit(self.DirectoryConfigGroupbox)
        self.WhiteTeamLineEdit.setObjectName("WhiteTeamLineEdit")
        self.gridLayout_3.addWidget(self.WhiteTeamLineEdit, 8, 1, 1, 1)
        self.RootDirectoryLabel = QtWidgets.QLabel(self.DirectoryConfigGroupbox)
        self.RootDirectoryLabel.setWordWrap(False)
        self.RootDirectoryLabel.setObjectName("RootDirectoryLabel")
        self.gridLayout_3.addWidget(self.RootDirectoryLabel, 1, 0, 1, 1)
        self.RooDirectoruLineEdit = QtWidgets.QLineEdit(self.DirectoryConfigGroupbox)
        self.RooDirectoruLineEdit.setObjectName("RooDirectoruLineEdit")
        self.gridLayout_3.addWidget(self.RooDirectoruLineEdit, 1, 1, 1, 1)
        self.WhiteTeamFolderLabel = QtWidgets.QLabel(self.DirectoryConfigGroupbox)
        self.WhiteTeamFolderLabel.setObjectName("WhiteTeamFolderLabel")
        self.gridLayout_3.addWidget(self.WhiteTeamFolderLabel, 8, 0, 1, 1)
        self.RedTeamLineEdit = QtWidgets.QLineEdit(self.DirectoryConfigGroupbox)
        self.RedTeamLineEdit.setObjectName("RedTeamLineEdit")
        self.gridLayout_3.addWidget(self.RedTeamLineEdit, 3, 1, 1, 1)
        self.RedTeamFolderLabel = QtWidgets.QLabel(self.DirectoryConfigGroupbox)
        self.RedTeamFolderLabel.setObjectName("RedTeamFolderLabel")
        self.gridLayout_3.addWidget(self.RedTeamFolderLabel, 3, 0, 1, 1)
        self.BlueTeamLineEdit = QtWidgets.QLineEdit(self.DirectoryConfigGroupbox)
        self.BlueTeamLineEdit.setObjectName("BlueTeamLineEdit")
        self.gridLayout_3.addWidget(self.BlueTeamLineEdit, 5, 1, 1, 1)
        self.BlueTeamToolButton = QtWidgets.QToolButton(self.DirectoryConfigGroupbox)
        self.BlueTeamToolButton.setObjectName("BlueTeamToolButton")
        self.gridLayout_3.addWidget(self.BlueTeamToolButton, 5, 3, 1, 1)
        self.RootDirectoryToolButton = QtWidgets.QToolButton(self.DirectoryConfigGroupbox)
        self.RootDirectoryToolButton.setObjectName("RootDirectoryToolButton")
        self.gridLayout_3.addWidget(self.RootDirectoryToolButton, 1, 3, 1, 1)
        self.RedTeamToolButton = QtWidgets.QToolButton(self.DirectoryConfigGroupbox)
        self.RedTeamToolButton.setObjectName("RedTeamToolButton")
        self.gridLayout_3.addWidget(self.RedTeamToolButton, 3, 3, 1, 1)
        self.BlueTeamFolderLabel = QtWidgets.QLabel(self.DirectoryConfigGroupbox)
        self.BlueTeamFolderLabel.setObjectName("BlueTeamFolderLabel")
        self.gridLayout_3.addWidget(self.BlueTeamFolderLabel, 5, 0, 1, 1)
        self.WhiteTeamToolButton = QtWidgets.QToolButton(self.DirectoryConfigGroupbox)
        self.WhiteTeamToolButton.setObjectName("WhiteTeamToolButton")
        self.gridLayout_3.addWidget(self.WhiteTeamToolButton, 8, 3, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem24, 9, 1, 1, 1)
        self.gridLayout_2.addWidget(self.DirectoryConfigGroupbox, 2, 0, 3, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.gridLayout_2.addItem(spacerItem25, 7, 0, 2, 1)
        self.StartIngestionPushButton = QtWidgets.QPushButton(self.DirectoryConfigView)
        self.StartIngestionPushButton.setObjectName("StartIngestionPushButton")
        self.gridLayout_2.addWidget(self.StartIngestionPushButton, 5, 0, 1, 1)
        self.StackView.addWidget(self.DirectoryConfigView)
        self.VectorConfigView = QtWidgets.QWidget()
        self.VectorConfigView.setObjectName("VectorConfigView")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.VectorConfigView)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.VectorConfigGroupBoxView = QtWidgets.QGroupBox(self.VectorConfigView)
        self.VectorConfigGroupBoxView.setAlignment(QtCore.Qt.AlignCenter)
        self.VectorConfigGroupBoxView.setObjectName("VectorConfigGroupBoxView")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.VectorConfigGroupBoxView)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.VectorConfigGroupBoxFieldArea = QtWidgets.QGroupBox(self.VectorConfigGroupBoxView)
        self.VectorConfigGroupBoxFieldArea.setObjectName("VectorConfigGroupBoxFieldArea")
        self.VC_TableView = QtWidgets.QTableWidget(self.VectorConfigGroupBoxFieldArea)
        self.VC_TableView.setGeometry(QtCore.QRect(15, 22, 743, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VC_TableView.sizePolicy().hasHeightForWidth())
        self.VC_TableView.setSizePolicy(sizePolicy)
        self.VC_TableView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VC_TableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.VC_TableView.setDragEnabled(False)
        self.VC_TableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.VC_TableView.setTextElideMode(QtCore.Qt.ElideRight)
        self.VC_TableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.VC_TableView.setGridStyle(QtCore.Qt.SolidLine)
        self.VC_TableView.setRowCount(50)
        self.VC_TableView.setObjectName("VC_TableView")
        self.VC_TableView.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.VC_TableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.VC_TableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VC_TableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VC_TableView.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(36, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(37, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(38, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(39, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(40, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(41, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(42, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(43, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(44, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(45, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(46, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(47, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(48, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.VC_TableView.setItem(49, 0, item)
        self.VC_TableView.horizontalHeader().setCascadingSectionResizes(False)
        self.VC_TableView.horizontalHeader().setDefaultSectionSize(240)
        self.VC_TableView.horizontalHeader().setSortIndicatorShown(True)
        self.VC_TableView.horizontalHeader().setStretchLastSection(False)
        self.VC_TableView.verticalHeader().setDefaultSectionSize(35)
        self.VC_AddVectorButton = QtWidgets.QPushButton(self.VectorConfigGroupBoxFieldArea)
        self.VC_AddVectorButton.setGeometry(QtCore.QRect(419, 613, 109, 32))
        self.VC_AddVectorButton.setObjectName("VC_AddVectorButton")
        self.VC_DeleteVectorButton = QtWidgets.QPushButton(self.VectorConfigGroupBoxFieldArea)
        self.VC_DeleteVectorButton.setGeometry(QtCore.QRect(530, 613, 124, 32))
        self.VC_DeleteVectorButton.setObjectName("VC_DeleteVectorButton")
        self.VC_EditVectorButton = QtWidgets.QPushButton(self.VectorConfigGroupBoxFieldArea)
        self.VC_EditVectorButton.setGeometry(QtCore.QRect(656, 613, 108, 32))
        self.VC_EditVectorButton.setObjectName("VC_EditVectorButton")
        self.VC_VectorTableLabel = QtWidgets.QLabel(self.VectorConfigGroupBoxFieldArea)
        self.VC_VectorTableLabel.setGeometry(QtCore.QRect(18, -10, 101, 41))
        self.VC_VectorTableLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.VC_VectorTableLabel.setObjectName("VC_VectorTableLabel")
        self.gridLayout_7.addWidget(self.VectorConfigGroupBoxFieldArea, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.VectorConfigGroupBoxView, 4, 0, 1, 1)
        self.StackView.addWidget(self.VectorConfigView)
        self.ChangeConfigView = QtWidgets.QWidget()
        self.ChangeConfigView.setObjectName("ChangeConfigView")
        self.ChangeConfigGroupBox = QtWidgets.QGroupBox(self.ChangeConfigView)
        self.ChangeConfigGroupBox.setGeometry(QtCore.QRect(29, -1, 771, 261))
        self.ChangeConfigGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ChangeConfigGroupBox.setObjectName("ChangeConfigGroupBox")
        self.CC_ChangeListLabel = QtWidgets.QLabel(self.ChangeConfigGroupBox)
        self.CC_ChangeListLabel.setGeometry(QtCore.QRect(30, 130, 91, 16))
        self.CC_ChangeListLabel.setObjectName("CC_ChangeListLabel")
        self.CC_ChangeListLineEdit = QtWidgets.QLineEdit(self.ChangeConfigGroupBox)
        self.CC_ChangeListLineEdit.setGeometry(QtCore.QRect(130, 130, 611, 21))
        self.CC_ChangeListLineEdit.setObjectName("CC_ChangeListLineEdit")
        self.CC_CommitPushButton = QtWidgets.QPushButton(self.ChangeConfigView)
        self.CC_CommitPushButton.setGeometry(QtCore.QRect(570, 280, 113, 32))
        self.CC_CommitPushButton.setObjectName("CC_CommitPushButton")
        self.CC_UndoPushButton = QtWidgets.QPushButton(self.ChangeConfigView)
        self.CC_UndoPushButton.setGeometry(QtCore.QRect(690, 280, 113, 32))
        self.CC_UndoPushButton.setObjectName("CC_UndoPushButton")
        self.StackView.addWidget(self.ChangeConfigView)
        self.IconConfigView = QtWidgets.QWidget()
        self.IconConfigView.setObjectName("IconConfigView")
        self.IconConfigGroupBox = QtWidgets.QGroupBox(self.IconConfigView)
        self.IconConfigGroupBox.setGeometry(QtCore.QRect(9, -1, 831, 711))
        self.IconConfigGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.IconConfigGroupBox.setObjectName("IconConfigGroupBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.IconConfigGroupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(9, 29, 801, 631))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.IconConfig_IT_VerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.IconConfig_IT_VerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.IconConfig_IT_VerticalLayout.setObjectName("IconConfig_IT_VerticalLayout")
        self.IC_IT_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_8)
        self.IC_IT_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.IC_IT_groupBox.setObjectName("IC_IT_groupBox")
        self.IC_IT_TableWidget = QtWidgets.QTableWidget(self.IC_IT_groupBox)
        self.IC_IT_TableWidget.setGeometry(QtCore.QRect(5, 21, 791, 601))
        self.IC_IT_TableWidget.setRowCount(50)
        self.IC_IT_TableWidget.setObjectName("IC_IT_TableWidget")
        self.IC_IT_TableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.IC_IT_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IC_IT_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IC_IT_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IC_IT_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(25, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(26, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(27, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(28, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(29, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(30, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(31, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(32, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(33, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(34, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(35, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(36, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(37, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(38, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(39, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(40, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(41, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(42, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(43, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(44, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(45, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.IC_IT_TableWidget.setItem(46, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(47, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(48, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.IC_IT_TableWidget.setItem(49, 0, item)
        self.IC_IT_TableWidget.horizontalHeader().setDefaultSectionSize(191)
        self.IconConfig_IT_VerticalLayout.addWidget(self.IC_IT_groupBox)
        self.IconConfigDeleteIconButton = QtWidgets.QPushButton(self.IconConfigGroupBox)
        self.IconConfigDeleteIconButton.setGeometry(QtCore.QRect(700, 670, 113, 32))
        self.IconConfigDeleteIconButton.setObjectName("IconConfigDeleteIconButton")
        self.IconConfigEditIconButton = QtWidgets.QPushButton(self.IconConfigGroupBox)
        self.IconConfigEditIconButton.setGeometry(QtCore.QRect(590, 670, 113, 32))
        self.IconConfigEditIconButton.setObjectName("IconConfigEditIconButton")
        self.IconConfigAddIconButton = QtWidgets.QPushButton(self.IconConfigGroupBox)
        self.IconConfigAddIconButton.setGeometry(QtCore.QRect(480, 670, 113, 32))
        self.IconConfigAddIconButton.setObjectName("IconConfigAddIconButton")
        self.StackView.addWidget(self.IconConfigView)
        self.gridLayout.addWidget(self.StackView, 0, 1, 1, 2)
        PICK_SettingView.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PICK_SettingView)
        self.statusbar.setObjectName("statusbar")
        PICK_SettingView.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PICK_SettingView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1281, 22))
        self.menubar.setObjectName("menubar")
        PICK_SettingView.setMenuBar(self.menubar)

        self.retranslateUi(PICK_SettingView)
        self.StackView.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(PICK_SettingView)

    def retranslateUi(self, PICK_SettingView):
        _translate = QtCore.QCoreApplication.translate
        PICK_SettingView.setWindowTitle(_translate("PICK_SettingView", "PICK Settings"))
        self.OV_GroupBox.setTitle(_translate("PICK_SettingView", "Option View"))
        self.OV_TeamConfigButton.setText(_translate("PICK_SettingView", "Team Configuration"))
        self.OV_EventConfigButton.setText(_translate("PICK_SettingView", "Event Configuration"))
        self.OV_DirectoryConfigButton.setText(_translate("PICK_SettingView", "Directory Configuration"))
        self.OV_VectorConfigButton.setText(_translate("PICK_SettingView", "Vector Configuration"))
        self.OV_ChangeConfigButton.setText(_translate("PICK_SettingView", "Change Configuration"))
        self.OV_IconConfigButton.setText(_translate("PICK_SettingView", "Icon Configuration"))
        self.IPAddressLineEdit.setText(_translate("PICK_SettingView", "129.108.202.0"))
        self.TeamConfigConnectpushButton.setText(_translate("PICK_SettingView", "Disconnect"))
        self.NoOfConnectionslineEdit.setText(_translate("PICK_SettingView", "12"))
        self.TeamConfigGroupBox.setTitle(_translate("PICK_SettingView", "Team Configuration"))
        self.LeadCheckBox.setText(_translate("PICK_SettingView", "Lead"))
        self.ConnectionStatus.setText(_translate("PICK_SettingView", "Connected"))
        self.LeadIPLabel.setText(_translate("PICK_SettingView", "Lead IP address:"))
        self.IPConnectionLabel.setText(_translate("PICK_SettingView", "No. of established connections to the lead\'s IP address:"))
        self.SaveEventPushButton.setText(_translate("PICK_SettingView", "Save Event"))
        self.EventConfigGroupBox.setTitle(_translate("PICK_SettingView", "Event Configuration"))
        self.EventNameLabel.setText(_translate("PICK_SettingView", "Event Name:"))
        self.EventDescriptionLabel.setText(_translate("PICK_SettingView", "Event Description:"))
        self.EventStartTimestampLabel.setText(_translate("PICK_SettingView", "Event start timestamp:"))
        self.EventEndTimestampLabel.setText(_translate("PICK_SettingView", "Event end timestamp:"))
        self.DirectoryConfigGroupbox.setTitle(_translate("PICK_SettingView", "Directory Configuration"))
        self.RootDirectoryLabel.setText(_translate("PICK_SettingView", "Root directory:"))
        self.WhiteTeamFolderLabel.setText(_translate("PICK_SettingView", "White team folder:"))
        self.RedTeamFolderLabel.setText(_translate("PICK_SettingView", "Red team folder:"))
        self.BlueTeamToolButton.setText(_translate("PICK_SettingView", "..."))
        self.RootDirectoryToolButton.setText(_translate("PICK_SettingView", "..."))
        self.RedTeamToolButton.setText(_translate("PICK_SettingView", "..."))
        self.BlueTeamFolderLabel.setText(_translate("PICK_SettingView", "Blue team folder:"))
        self.WhiteTeamToolButton.setText(_translate("PICK_SettingView", "..."))
        self.StartIngestionPushButton.setText(_translate("PICK_SettingView", "Start data ingestion"))
        self.VectorConfigGroupBoxView.setTitle(_translate("PICK_SettingView", "Vector configuration"))
        self.VC_TableView.setSortingEnabled(True)
        item = self.VC_TableView.horizontalHeaderItem(1)
        item.setText(_translate("PICK_SettingView", "Vector name"))
        item = self.VC_TableView.horizontalHeaderItem(2)
        item.setText(_translate("PICK_SettingView", "Vector description"))
        __sortingEnabled = self.VC_TableView.isSortingEnabled()
        self.VC_TableView.setSortingEnabled(False)
        self.VC_TableView.setSortingEnabled(__sortingEnabled)
        self.VC_AddVectorButton.setText(_translate("PICK_SettingView", "Add vector"))
        self.VC_DeleteVectorButton.setText(_translate("PICK_SettingView", "Delete vector"))
        self.VC_EditVectorButton.setText(_translate("PICK_SettingView", "Edit vector"))
        self.VC_VectorTableLabel.setText(_translate("PICK_SettingView", "      vector table"))
        self.ChangeConfigGroupBox.setTitle(_translate("PICK_SettingView", "Change configuration"))
        self.CC_ChangeListLabel.setText(_translate("PICK_SettingView", "Change list:"))
        self.CC_CommitPushButton.setText(_translate("PICK_SettingView", "Commit"))
        self.CC_UndoPushButton.setText(_translate("PICK_SettingView", "Undo"))
        self.IconConfigGroupBox.setTitle(_translate("PICK_SettingView", "Icon configuration"))
        self.IC_IT_groupBox.setTitle(_translate("PICK_SettingView", "Icon table"))
        self.IC_IT_TableWidget.setSortingEnabled(True)
        item = self.IC_IT_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PICK_SettingView", "Icon name"))
        item = self.IC_IT_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PICK_SettingView", "Icon source"))
        item = self.IC_IT_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PICK_SettingView", "Image preview"))
        __sortingEnabled = self.IC_IT_TableWidget.isSortingEnabled()
        self.IC_IT_TableWidget.setSortingEnabled(False)
        self.IC_IT_TableWidget.setSortingEnabled(__sortingEnabled)
        self.IconConfigDeleteIconButton.setText(_translate("PICK_SettingView", "Delete Icon"))
        self.IconConfigEditIconButton.setText(_translate("PICK_SettingView", "Edit Icon"))
        self.IconConfigAddIconButton.setText(_translate("PICK_SettingView", "Add Icon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PICK_SettingView = QtWidgets.QMainWindow()
    ui = Ui_PICK_SettingView()
    ui.setupUi(PICK_SettingView)
    PICK_SettingView.show()
    sys.exit(app.exec_())
